const data = {
    products: [
        {
            name: 'Nije Slim shirt',
            slug: "nije-slim-shir",
            category: 'shirts',
            image: '/images/lp2.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Niek',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nije Slim shirt',
            slug: "nije-slim-shi",
            category: 'shirts',
            image: '/images/lp3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Niek',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nije Slim shirt',
            slug: "nije-slim-sh",
            category: 'shirts',
            image: '/images/lp4.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Niek',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nije Slim shirt',
            slug: "nije-slim-s",
            category: 'shirts',
            image: '/images/lp5.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Niek',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nije Slim shirt',
            slug: "nije-slim-",
            category: 'shirts',
            image: '/images/m1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Niek',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nije Slim shirt',
            slug: "nije-slim",
            category: 'shirts',
            image: '/images/m2.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Niek',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },
        {
            name: 'Nije Slim shirt',
            slug: "nije-sli",
            category: 'shirts',
            image: '/images/m3.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Niek',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality shirt',
        },

    ]
}
export default data